# Generated by Django 3.1 on 2020-08-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
